#!/bin/sh

# CONTEXT: GUEST during CONSTRUCTION as ROOT
# PURPOSE: Install controller base required packages

set -e
set -o xtrace

export DEBIAN_FRONTEND=noninteractive
# cartman: we add random ppa's in the ghetto
add-apt-repository ppa:rwky/redis -y
apt-get update
apt-get install -y redis-server